### ISSUE TITLE
The requests to the backend should contain less parameters

### ISSUE THREAD

**Issue by Cicero-Henrique** [marcosmatioli/ragnarok-wiki#18]
Will be a great improvement if the API requests contain fewer parameters, for instance, if I want to select "dragons" with the "water property, I think the request should be /api/monsters?name=&page=1&per_page=60&dragon=true&water=true, instead /api/monsters?name=&page=1&per_page=60&formless=false&undead=false&brute=false&plant=false&insect=false&fish=false&demon=false&human=false&angel=false&dragon=true&neutral=false&water=true&earth=false&fire=false&wind=false&poison=false&holy=false&dark=false&ghost=false&maledict=false. Even the tests for the application will be easier.

**Comment by raphaelsander** [comment]
Hi @Cicero-Henrique,

What do you think about this query? Based on this [Medium](https://tech-depth-and-breadth.medium.com/accessing-lists-as-query-param-in-fastapi-1e506a411b2e) share idea.

`/api/monsters?name=&page=1&per_page=60&element=dragon,fire&race=undead,plant`

Checking the code, we did this long query string because in JS was so simple pass the state of each toggle button stead of append a list, maybe because I am not good at JS at all 😄:

```js
const checkboxQueryString = getCheckboxQueryString();
const response = await fetch(`${API_ADDRESS}/api/monsters?name=${searchName}&page=${currentPage}&per_page=${perPage}&${checkboxQueryString}`);
```

```js
function getCheckboxQueryString() {
    const checkboxStates = [];
    checkboxes.forEach(checkbox => {
        checkboxStates.push(`${checkbox.id}=${checkbox.checked}`);
    });
    return checkboxStates.join('&');
}
```

But I believe that we can improve in both sides, frontend and backend.
I will work on it this week, let you know soon.

**Comment by Cicero-Henrique** [comment]
This could be a good approach.

**Comment by raphaelsander** [comment]
Hi @Cicero-Henrique,

You can checkout the branch **improve-api** and do a `docker compose up -d --build`.
Let me know if it's ok this implementation.

**Comment by raphaelsander** [comment]
Hi @marcosmatioli,

Could you review and approve it? This implementation is tested and working fine.
Let me merge, thanks.
